site_name: EuroCC Knowledge Pool
nav:
    - Home: index.md
    - HPC 101: getstarted.md
    - Best practices: best.md
    - HPC programming: progr.md
    - Choose your HPC: choice.md
docs_dir: develop
site_dir: docs
plugins:
    - search
    - pdf-export:
        combined: true
        media_type: print
extra_css:
    - extra.css
theme: 
    name: material
    custom_dir: develop/overrides
    logo: 'img/boxLogo.png'
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg