site_name: EuroCC Knowledge Pool
nav:
    - Home: index.md
    - Best practices: best.md
    - Coding on HPC: progr.md
    - Software: software.md
    - Literature: literature.md
    - Danish HPCs: danmark.md
    - Hardware: hardware.md
plugins:
    - search
    - pdf-export:
        combined: true
        media_type: print
extra_css:
    - extra.css
theme: 
    name: material
    custom_dir: docs/overrides
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg